@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class GreenTrackerException
{
+ GreenTrackerException(message: String)
}

Exception <|-- GreenTrackerException

interface Comparable<Verbrauch>
{
+ {abstract} compareTo(o: Verbrauch): int
}

Comparable <|.. Verbrauch

class Wasserverbrauch extends Verbrauch
{
- aktuellerWasserPreis: double
- kubikmeternVerbrauchWasser: double
+ Wasserverbrauch(aktuellerWasserPreis: double,kubikmeternVerbrauchWasser: double)
+ getAktuellerWasserPreis(): double
+ getKubikmeternVerbrauchWasser(): double
+ preis(): double
+ ausstoß(): double
+ setAktuellerWasserPreis(aktuellerWasserPreis: double): void
+ setKubikmeternVerbrauchWasser(kubikmeternVerbrauchWasser: double): void
+ toString(): String
}

class GasVerbrauch extends Verbrauch
{
- aktuellerGasPreis: double
- kubikmeternVerbrauchGas: double
+ Wasserverbrauch(aktuellerGasPreis: double,kubikmeternVerbrauchGas: double)
+ getAktuellerWasserPreis(): double
+ getKubikmeternVerbrauchGas(): double
+ preis(): double
+ ausstoß(): double
+ setAktuellerGasPreis(aktuellerGasPreis: double): void
+ setKubikmeternVerbrauchGas(kubikmeternVerbrauchGas: double): void
+ toString(): String
}

class StromVerbrauch extends Verbrauch{
- aktuellerStromPreis: double
- kilowattstunden: double
+ StromVerbrauch(aktuellerStromPreis: double,kilowattstunden: double)
+ getAktuellerStromPreis(): double
+ getKilowattstunden(): double
+ preis(): double
+ ausstoß(): double
+ setAktuellerStromPreis(aktuellerStromPreis: double): void
+ setKilowattstunden(kilowattstunden: double): void
+ toString(): String
}

abstract class Verbrauch
{
- taetigkeit: String
- dauer: double
- anzahlTeatigkeit: int
+ Verbrauch()
+ Verbrauch(taetigkeit: String, dauer: double, anzahlTeatigkeit: int)
+ getTaetigkeit(): String
+ getDauer(): double
+ getAnzahlTeatigkeit(): int
+ setTaetigkeit(taetigkeit: String): void
+ setDauer(dauer: double): void
+ setAnzahlTeatigkeit(anzahlTeatigkeit: int): void
+ {abstract} preis(): double
+ {abstract} ausstoß(): double
+ toString(): String
}

class GreenTracker
{
- name: String
- verbauche: List<Verbrauch>
+ GreenTracker(name: String)
+ getVerbrauch(index: int): Verbrauch
+ hinzufuegen(verbauch: Verbrauch): boolean
+ entfernen(verbauch: Verbrauch): boolean
+ entfernen(bezeichnung: String): int
+ berechneGesamtEmisson(): double
+ berechneVerbrauchEmisson(): double
+ berechneGesamtPreis(): double
+ berechneVerbrauchPreis(): double
+ writeVerbraucheToCSV(): void
+ save(): void
+ readVerbraucheFromCSV(): void
+ sortieren(): void
+ sortierenNachBezeichnung(): void
+ toString(): String
+ toCSVString(): String
}

GreenTracker --> Verbrauch

together{
class Verbrauch
class GreenTracker
}
GreenTracker -[hidden] Verbrauch

together{
class GreenTracker
class GreenTrackerException
}
GreenTrackerException -[hidden] GreenTracker

@enduml
